# Generated by Django 5.2 on 2026-07-09 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('color', models.CharField(default='#cbd5e1', help_text='For consistent chart coloring', max_length=50, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.CharField(choices=[('emi', 'EMI'), ('subscription', 'Subscription'), ('renewal', 'Renewal')], max_length=20, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, verbose_name='Frequency')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='NULL if indefinite (most subscriptions), set for EMIs with fixed tenure', null=True, verbose_name='End Date')),
                ('next_due_date', models.DateField(verbose_name='Next Due Date')),
                ('total_installments', models.PositiveIntegerField(blank=True, help_text='NULL for subscriptions/renewals, set for EMIs', null=True, verbose_name='Total Installments')),
                ('installments_paid', models.PositiveIntegerField(blank=True, help_text='NULL for subscriptions/renewals, tracked for EMIs', null=True, verbose_name='Installments Paid')),
                ('active', models.BooleanField(default=True, help_text='Allows canceling something without deleting its history', verbose_name='Active')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_items', to='expense.category', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_items', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Recurring Item',
                'verbose_name_plural': 'Recurring Items',
                'ordering': ['next_due_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('period_label', models.CharField(help_text="e.g. '2026-07' for monthly, '2026' for yearly", max_length=50, verbose_name='Period Label')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Usually matches recurring_items.amount, but allows for fee hikes/late fees', max_digits=12, verbose_name='Amount')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('recurring_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='expense.recurringitem', verbose_name='Recurring Item')),
            ],
            options={
                'verbose_name': 'Recurring Payment',
                'verbose_name_plural': 'Recurring Payments',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10, verbose_name='Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='expense.category', verbose_name='Category')),
                ('recurring_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='expense.recurringpayment', verbose_name='Recurring Payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_payments', to='expense.transaction', verbose_name='Transaction'),
        ),
    ]
